### ISSUE TITLE
ProducerTopic::produce and ::producev throw Exception too

### ISSUE THREAD

**Issue by damianwadley** [kwn/php-rdkafka-stubs#42]
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-producertopic.produce.html
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-producertopic.producev.html

As prevalent as Exception is, there may be other methods that also throw Exception and aren't listed as such in the stubs, but those two are the ones I'm currently aware of.

**Comment by damianwadley** [comment]
@kwn Anything you need from me?

**Comment by kwn** [comment]
Hi @damianwadley 

Apologies, didn't have time to review it. I just merged your PR and will tag a new version soon. Thank you for your contribution!
