### ISSUE TITLE
PHPStorm integration

### ISSUE THREAD

**Issue by clarkeash** [kwn/php-rdkafka-stubs#8]
Hi, I dont know what IDE you use but have you thought about adding a PR for PHPStorm to https://github.com/JetBrains/phpstorm-stubs so it has this by default, if not, are you okay for me to copy your stubs and submit the PR myself?

Thanks

**Comment by kwn** [comment]
Hi @clarkeash, sorry for the late reply.

Thank you for the suggestion. I thought about it and I decided to maintain a separate repository with Kafka stubs, even though I use Phpstorm and I'm big fan of it. There are few reasons for that:
- it allows to use it by developers who prefers different IDE (I know that majority uses phpstorm, but still)
- it allows developers to install stubs corresponding to a specific version of RdKafka (I know that usually developers use the latest version but still)
- it also allows me to maintain the open source project, used by other developers. It's just fun :)

Of course I can't stop you from making a PR against Jetbrains stubs, but in that case no one will be able to guarantee updates, and probably it will cause some conflicts with projects which have already `kwn/php-rdkafka-stubs` installed.
